# Generated by Django 4.2.5 on 2023-09-29 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_alter_client_uid_alter_project_cid_alter_project_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 12, 33, 51, 83899)),
        ),
    ]
