# Generated by Django 4.2.5 on 2023-09-29 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 14, 12, 1, 867190)),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 14, 12, 1, 867190)),
        ),
    ]
