# Generated by Django 4.2.4 on 2023-10-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_alter_product_cat_alter_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdetails',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
