# Generated by Django 4.2.4 on 2023-10-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_product_pdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default=0, upload_to='appimage/product', verbose_name='Product Image'),
            preserve_default=False,
        ),
    ]
